In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv('D:\\Download_from_Chrome\\house-prices-advanced-regression-techniques\\train.csv')
test = pd.read_csv('D:\\Download_from_Chrome\\house-prices-advanced-regression-techniques\\test.csv')

In [5]:
train.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
0         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
1         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
2         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
3         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
4         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  
3      2   2006        WD        Abnorml     140000  
4     12   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [6]:
test.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities      ...       ScreenPorch PoolArea PoolQC  Fence  \
0         Lvl    AllPub      ...               120        0    NaN  MnPrv   
1         Lvl    AllPub      ...                 0        0    NaN    NaN   
2         Lvl    AllPub      ...                 0        0    NaN  MnPrv   
3         Lvl    AllPub      ...                 0        0    NaN    NaN   
4         HLS    AllPub      ...               144        0    NaN    NaN   

  MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0         NaN       0      6    2010        WD         Normal  
1        Gar2   12500      6    2010        WD         Normal  
2         NaN       0      3    2010        WD         Normal  
3         NaN       0      6    2010        WD         Normal  
4         NaN       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [9]:
train.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType          8
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
                 ... 
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive

In [8]:
test.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       227
LotArea             0
Street              0
Alley            1352
LotShape            0
LandContour         0
Utilities           2
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         1
Exterior2nd         1
MasVnrType         16
MasVnrArea         15
ExterQual           0
ExterCond           0
Foundation          0
                 ... 
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         1
TotRmsAbvGrd        0
Functional          2
Fireplaces          0
FireplaceQu       730
GarageType         76
GarageYrBlt        78
GarageFinish       78
GarageCars          1
GarageArea          1
GarageQual         78
GarageCond

In [10]:
def clean(data):
    data = data.drop(['Alley','FireplaceQu','PoolQC','Fence','MiscFeature'],1)
    data = data. dropna()
    return data

In [11]:
train = clean(train)
test = clean(test)

In [15]:
Y_train = train['SalePrice']
train = train.drop(['SalePrice'],1)

In [27]:
Y_train.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

In [22]:
data = pd.concat([train,test])

In [23]:
data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0   1          60       RL         65.0     8450   Pave      Reg         Lvl   
1   2          20       RL         80.0     9600   Pave      Reg         Lvl   
2   3          60       RL         68.0    11250   Pave      IR1         Lvl   
3   4          70       RL         60.0     9550   Pave      IR1         Lvl   
4   5          60       RL         84.0    14260   Pave      IR1         Lvl   

  Utilities LotConfig      ...       OpenPorchSF EnclosedPorch 3SsnPorch  \
0    AllPub    Inside      ...                61             0         0   
1    AllPub       FR2      ...                 0             0         0   
2    AllPub    Inside      ...                42             0         0   
3    AllPub    Corner      ...                35           272         0   
4    AllPub       FR2      ...                84             0         0   

  ScreenPorch PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition  
0           0        0       0       2    2008        WD         Normal  
1           0        0       0       5    2007        WD         Normal  
2           0        0       0       9    2008        WD         Normal  
3           0        0       0       2    2006        WD        Abnorml  
4           0        0       0      12    2008        WD         Normal  

[5 rows x 75 columns]

In [24]:
categorical = data.select_dtypes(exclude = np.number)
numerical = data.select_dtypes(include = np.number)
categorical= pd.get_dummies(categorical)
X = pd.concat([numerical,categorical],1)

In [25]:
X_train = X.iloc[0:1094,:]
X_test = X.iloc[1094:2203,:]


In [28]:

from sklearn.linear_model import LinearRegression
lin_reg= LinearRegression()

lr_model= lin_reg.fit(X_train,Y_train)
y_pred_lr= lr_model.predict(X_test)

In [29]:
y_pred_lr

array([118043.67474365, 145505.10755157, 189574.57354736, ...,
        84248.5577774 , 190992.21409607, 230566.53569412])

In [31]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(random_state = 42)

dt_model= dt.fit(X_train,Y_train)
y_pred_dt= dt_model.predict(X_test)

In [32]:
y_pred_dt

array([129900., 163000., 197500., ...,  75000., 142000., 190000.])

In [34]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators = 100, random_state = 42)

rf_model= rf.fit(X_train,Y_train)
y_pred_rf= rf_model.predict(X_test)

In [37]:
y_pred_rf

array([123646.58, 152225.  , 186215.15, ...,  89125.29, 148505.84,
       235040.92])